const $=s=>document.querySelector(s);let profiles=[],activeProfileId="default",settings={showFloatingButton:true,fillOnlyEmpty:true},editingId=null;
const store=(v)=>new Promise(r=>chrome.storage.local.set(v,r)); const get=(k)=>new Promise(r=>chrome.storage.local.get(k,r));
document.addEventListener("DOMContentLoaded",init);
async function init(){const d=await get(["profiles","activeProfileId","settings","applications","savedAnswers","authSession","supabaseUrl","supabaseAnonKey"]);profiles=d.profiles||[];activeProfileId=d.activeProfileId||profiles[0]?.id||"default";settings=d.settings||settings;if(!profiles.length){profiles=[emptyProfile("General")];activeProfileId=profiles[0].id;await store({profiles,activeProfileId});}render();bind();loadSettings(d);showTab("home");}
function emptyProfile(name){return{id:"p_"+Date.now()+"_"+Math.random().toString(36).slice(2,7),name,fullName:"",email:"",phone:"",linkedin:"",github:"",portfolio:"",currentTitle:"",currentCompany:"",yearsExperience:"",education:"",skills:"",salaryExpectation:"",address:"",city:"",state:"",zip:"",country:"",coverLetterTemplate:"Dear Hiring Manager,\n\nI am excited to apply for {{role}} at {{company}}.\n\nBest regards,\n{{name}}",resumeText:"",resumeFileName:"",resumeFileBase64:"",answers:{}}}
function active(){return profiles.find(p=>p.id===activeProfileId)||profiles[0]}
function render(){const s=$("#profileSelect");s.innerHTML=profiles.map(p=>`<option value="${p.id}" ${p.id===activeProfileId?"selected":""}>${esc(p.name)}</option>`).join("");const p=active();$("#preview").textContent=`${p.fullName||"—"} · ${p.email||"—"} · ${p.currentTitle||"—"}`;renderTracker()}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$("#profileSelect").onchange=async e=>{activeProfileId=e.target.value;await store({activeProfileId});render()};$("#autofillBtn").onclick=autofill;$("#editProfileBtn").onclick=()=>edit(active());$("#newProfileBtn").onclick=()=>edit(emptyProfile("New Profile"),true);$("#profileForm").onsubmit=saveProfile;$("#syncBtn").onclick=sync;$("#saveConfigBtn").onclick=saveConfig;$("#loginBtn").onclick=login;$("#signupBtn").onclick=signup;$("#logoutBtn").onclick=logout;$("#deleteDataBtn").onclick=deleteData;$("#searchJobsBtn").onclick=searchJobs;$("#answerBtn").onclick=()=>aiQuestion();$("#tailorBtn").onclick=()=>aiResume("tailor_resume");$("#coverBtn").onclick=()=>aiResume("cover_letter");$("#scoreBtn").onclick=()=>aiResume("match_score");$("#fabToggle").onchange=e=>{settings.showFloatingButton=e.target.checked;store({settings});chrome.tabs.query({active:true,currentWindow:true},t=>t[0]&&chrome.tabs.sendMessage(t[0].id,{action:"toggleFab",show:e.target.checked}).catch(()=>{}))};$("#emptyToggle").onchange=e=>{settings.fillOnlyEmpty=e.target.checked;store({settings})}}
function showTab(id){document.querySelectorAll(".panel").forEach(x=>x.classList.toggle("hidden",x.id!==id));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===id))}
async function autofill(){try{const[t]=await chrome.tabs.query({active:true,currentWindow:true});const r=await chrome.tabs.sendMessage(t.id,{action:"triggerAutofill"});$("#status").textContent=`Filled ${r?.filled||0} field(s).`;}catch(e){$("#status").textContent="This page blocks extensions (for example chrome:// pages). Try a normal website.";}}
function edit(p,isNew=false){editingId=isNew?null:p.id;const x=isNew?p:active();for(const [k,id] of Object.entries({name:"f_name",fullName:"f_fullName",email:"f_email",phone:"f_phone",linkedin:"f_linkedin",github:"f_github",portfolio:"f_portfolio",currentTitle:"f_currentTitle",currentCompany:"f_currentCompany",yearsExperience:"f_yearsExperience",education:"f_education",skills:"f_skills",city:"f_city",state:"f_state",country:"f_country",resumeText:"f_resumeText",coverLetterTemplate:"f_coverLetterTemplate"}))$("#"+id).value=x[k]||"";$("#f_answers").value=JSON.stringify(x.answers||{},null,2);$("#resumeFileName").textContent=x.resumeFileName||"No PDF stored";showTab("settings")}
async function saveProfile(e){e.preventDefault();const p=active(),data={name:$("#f_name").value.trim()||"General",fullName:$("#f_fullName").value.trim(),email:$("#f_email").value.trim(),phone:$("#f_phone").value.trim(),linkedin:$("#f_linkedin").value.trim(),github:$("#f_github").value.trim(),portfolio:$("#f_portfolio").value.trim(),currentTitle:$("#f_currentTitle").value.trim(),currentCompany:$("#f_currentCompany").value.trim(),yearsExperience:$("#f_yearsExperience").value.trim(),education:$("#f_education").value.trim(),skills:$("#f_skills").value.trim(),city:$("#f_city").value.trim(),state:$("#f_state").value.trim(),country:$("#f_country").value.trim(),resumeText:$("#f_resumeText").value.trim(),coverLetterTemplate:$("#f_coverLetterTemplate").value.trim(),answers:parseAnswers($("#f_answers").value)};const f=$("#f_resumeFile").files[0];if(f){if(!f.name.toLowerCase().endsWith(".pdf"))return alert("PDF only");data.resumeFileName=f.name;data.resumeFileBase64=await readFile(f)}else{data.resumeFileName=p.resumeFileName||"";data.resumeFileBase64=p.resumeFileBase64||""}if(editingId){const i=profiles.findIndex(x=>x.id===editingId);profiles[i]={...profiles[i],...data}}else{const n={...emptyProfile(data.name),...data};profiles.push(n);activeProfileId=n.id}await store({profiles,activeProfileId});render();alert("Profile saved")}
function parseAnswers(v){if(!v.trim())return{};try{const x=JSON.parse(v);if(!x||Array.isArray(x)||typeof x!=="object")throw 0;return x}catch{return alert("Answers must be valid JSON."),{}}}
function readFile(f){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function loadSettings(d){$("#sbUrl").value=d.supabaseUrl||JOBPRO_SUPABASE.url;$("#sbKey").value=d.supabaseAnonKey||"";$("#fabToggle").checked=settings.showFloatingButton!==false;$("#emptyToggle").checked=settings.fillOnlyEmpty!==false;$("#authStatus").textContent=d.authSession?.user?.email?("Logged in as "+d.authSession.user.email):"Not logged in"}
async function saveConfig(){await store({supabaseUrl:$("#sbUrl").value.trim().replace(/\/$/,""),supabaseAnonKey:$("#sbKey").value.trim()});alert("Connection saved")}
async function login(){try{const r=await sbLogin($("#authEmail").value.trim(),$("#authPassword").value);$("#authStatus").textContent=r.user?.email?"Logged in as "+r.user.email:"Logged in";await sync()}catch(e){alert(e.message)}}
async function signup(){try{const r=await sbSignUp($("#authEmail").value.trim(),$("#authPassword").value);$("#authStatus").textContent=r.access_token?"Account created and logged in":"Check your email to confirm the account"}catch(e){alert(e.message)}}
async function logout(){await sbLogout();$("#authStatus").textContent="Not logged in"}
async function sync(){try{const r=await sbSyncLocal();$("#status").textContent=r.ok?"Synced with Supabase.":"Log in to sync.";const d=await get(["profiles","applications","savedAnswers"]);profiles=d.profiles||profiles;render()}catch(e){$("#status").textContent=e.message}}
async function getJob(){try{const[t]=await chrome.tabs.query({active:true,currentWindow:true});return await chrome.tabs.sendMessage(t.id,{action:"getJobInfo"})}catch{return{}}}
function safeContext(p){return{resume:sanitizeAiText(p.resumeText||""),skills:p.skills||"",education:p.education||"",title:p.currentTitle||"",company:p.currentCompany||"",yearsExperience:p.yearsExperience||""}}
function sanitizeAiText(value){
  let s=String(value||"");
  s=s.replace(/\\b(?:\\+?91[-\\s]?)?[6-9]\\d{9}\\b/g,"[PHONE REDACTED]");
  s=s.replace(/\\b[A-Z]{5}\\d{4}[A-Z]\\b/gi,"[PAN REDACTED]");
  s=s.replace(/\\b\\d{4}[ -]?\\d{4}[ -]?\\d{4}\\b/g,"[ID REDACTED]");
  s=s.replace(/\\b(?:passport|aadhaar|aadhar|driving license|driver.?s license|ssn|government id)\\s*[:#-]?\\s*[^\\n,;|]+/gi,"[ID REDACTED]");
  s=s.replace(/\\b(?:salary|ctc|compensation|expected pay|expected salary)\\s*[:#-]?\\s*[^\\n,;|]+/gi,"[SALARY REDACTED]");
  s=s.replace(/\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b/gi,"[EMAIL REDACTED]");
  s=s.replace(/^(?:address|home address|street address|residential address)\\s*[:#-].*$/gim,"[ADDRESS REDACTED]");
  return s.slice(0,18000);
}
async function consent(){const d=await get(["aiConsent"]);if(d.aiConsent)return true;const ok=confirm("JobPro AI will send your resume text and non-sensitive profile facts to the configured AI provider through Supabase. Phone, address, IDs and salary are excluded. Continue?");if(ok)await store({aiConsent:true});return ok}
async function aiQuestion(){if(!(await consent()))return;const q=prompt("Paste the application question.");if(!q)return;try{const p=active(),j=await getJob(),r=await sbAi("answer_question",{question:q,context:{...safeContext(p),job:j}});$("#aiOutput").value=r.result||"";const answers=(await get(["savedAnswers"])).savedAnswers||[];answers.unshift({question_hash:await hash(q),question:q,answer:r.result||"",updated_at:new Date().toISOString()});await store({savedAnswers:answers.slice(0,100)});}catch(e){alert(e.message)}}
async function aiResume(action){if(!(await consent()))return;try{const p=active(),j=await getJob(),r=await sbAi(action,{job:j,resume:safeContext(p)});$("#aiOutput").value=r.result||""}catch(e){alert(e.message)}}
async function searchJobs(){try{const r=await sbFetchJobs($("#jobQuery").value||"Power BI",$("#jobLocation").value||"Delhi");const list=r.jobs||[];$("#jobsList").innerHTML=list.map(j=>`<div class="job"><b>${esc(j.title)}</b><span>${esc(j.company)} · ${esc(j.location)}</span><small>${esc(j.source)} · ${j.posted_at?new Date(j.posted_at).toLocaleDateString():""}</small><br><button data-url="${esc(j.url)}" data-title="${esc(j.title)}" data-company="${esc(j.company)}">Open</button> <button data-save="${esc(j.url)}" data-title="${esc(j.title)}" data-company="${esc(j.company)}">Save</button></div>`).join("");$("#jobsList").querySelectorAll("[data-url]").forEach(b=>b.onclick=()=>chrome.tabs.create({url:b.dataset.url}));$("#jobsList").querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>saveApplication({url:b.dataset.save,title:b.dataset.title,company:b.dataset.company,status:"saved"}))}catch(e){alert(e.message)}}
async function saveApplication(a){const d=await get(["applications"]);const apps=d.applications||[];apps.unshift({...a,id:"local_"+Date.now()});await store({applications:apps});renderTracker()}
async function renderTracker(){const d=await get(["applications"]);const apps=d.applications||[];$("#trackerList").innerHTML=apps.slice(0,25).map(a=>`<div class="job"><b>${esc(a.title||"Untitled")}</b><span>${esc(a.company||"")} · ${esc(a.status||"saved")}</span><br><button data-open="${esc(a.url||"")}">Open</button></div>`).join("")||"<div class='status'>No applications saved.</div>";$("#trackerList").querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>b.dataset.open&&chrome.tabs.create({url:b.dataset.open}))}
async function hash(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s.trim().toLowerCase()));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function esc(s){return String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}

async function deleteData(){if(!confirm("Delete your synced JobPro cloud data? This cannot be undone."))return;try{await sbFetch("/functions/v1/delete_data",{method:"POST"});await store({profiles:[emptyProfile("General")],activeProfileId:"default",applications:[],savedAnswers:[],aiConsent:false});profiles=[emptyProfile("General")];activeProfileId=profiles[0].id;render();alert("Synced JobPro data deleted.");}catch(e){alert(e.message)}}
