// Minimal Supabase REST client for MV3.
const JOBPRO_SUPABASE={url:"https://kbsksavehfedjskpengb.supabase.co",anonKey:"sb_publishable_5nLLO3E5hD9x9Yv6yF8WuA_Hwia_8Qc"};
const storageGet=keys=>new Promise(r=>chrome.storage.local.get(keys,r));
const storageSet=value=>new Promise(r=>chrome.storage.local.set(value,r));
async function getSupabaseConfig(){const s=await storageGet(["supabaseUrl","supabaseAnonKey","authSession"]);return{url:s.supabaseUrl||JOBPRO_SUPABASE.url,anonKey:s.supabaseAnonKey||JOBPRO_SUPABASE.anonKey,session:s.authSession||null}}
async function sbFetch(path,options={}){const cfg=await getSupabaseConfig();if(!cfg.url||!cfg.anonKey)throw new Error("Configure Supabase URL and publishable/anon key in Settings.");const headers={apikey:cfg.anonKey,...(options.headers||{})};if(cfg.session?.access_token)headers.Authorization="Bearer "+cfg.session.access_token;if(options.body&&!headers["Content-Type"])headers["Content-Type"]="application/json";const res=await fetch(cfg.url.replace(/\/$/,"")+path,{...options,headers});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{}if(!res.ok)throw new Error(data?.message||data?.error_description||data?.error||text||"Supabase request failed");return data}
async function sbSignUp(email,password){const cfg=await getSupabaseConfig();const res=await fetch(cfg.url+"/auth/v1/signup",{method:"POST",headers:{apikey:cfg.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.msg||data.error_description||"Sign up failed");if(data.access_token)await storageSet({authSession:data});return data}
async function sbLogin(email,password){const cfg=await getSupabaseConfig();const res=await fetch(cfg.url+"/auth/v1/token?grant_type=password",{method:"POST",headers:{apikey:cfg.anonKey,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error_description||data.msg||"Login failed");await storageSet({authSession:data});return data}
async function sbLogout(){const cfg=await getSupabaseConfig();if(cfg.session?.access_token&&cfg.anonKey)await fetch(cfg.url+"/auth/v1/logout",{method:"POST",headers:{apikey:cfg.anonKey,Authorization:"Bearer "+cfg.session.access_token}});await storageSet({authSession:null})}
function sbUserId(session){return session?.user?.id||(session?.access_token?JSON.parse(atob(session.access_token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/"))).sub:"")}
async function sbQuery(table,query="",options={}){return sbFetch("/rest/v1/"+table+(query?"?"+query:""),options)}
async function sbUpsert(table,rows,onConflict){return sbQuery(table,onConflict?"on_conflict="+encodeURIComponent(onConflict):"",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(Array.isArray(rows)?rows:[rows])})}
async function sbUploadResume(userId,fileName,dataUrl){const cfg=await getSupabaseConfig();const comma=dataUrl.indexOf(",");const raw=comma>-1?dataUrl.slice(comma+1):dataUrl;const meta=comma>-1?dataUrl.slice(0,comma):"";const mime=(meta.match(/data:([^;]+)/)||[])[1]||"application/pdf";const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));const safe=fileName.replace(/[^a-zA-Z0-9._-]/g,"_");const path=userId+"/"+Date.now()+"-"+safe;const res=await fetch(cfg.url+"/storage/v1/object/jobpro-resumes/"+encodeURIComponent(path),{method:"POST",headers:{apikey:cfg.anonKey,Authorization:"Bearer "+cfg.session.access_token,"Content-Type":mime,"x-upsert":"false"},body:bytes});if(!res.ok)throw new Error("Resume upload failed");return path}
async function sbSyncLocal(){const cfg=await getSupabaseConfig();if(!cfg.session?.access_token)return{ok:false,reason:"not_logged_in"};const userId=sbUserId(cfg.session);const local=await storageGet(["profiles","activeProfileId","applications","savedAnswers"]);const profiles=local.profiles||[];for(const p of profiles){await sbUpsert("jobpro_profiles",{user_id:userId,name:p.name||"General",full_name:p.fullName||"",email:p.email||"",phone:p.phone||"",links:{linkedin:p.linkedin||"",github:p.github||"",portfolio:p.portfolio||""},answers:p.answers||{}},"user_id,name");if(p.resumeFileBase64){try{const path=await sbUploadResume(userId,p.resumeFileName||"resume.pdf",p.resumeFileBase64);await sbUpsert("jobpro_resumes",{user_id:userId,file_path:path,parsed_text:p.resumeText||"",is_default:true})}catch(_){}}}const answers=local.savedAnswers||[];for(const a of answers)await sbUpsert("jobpro_saved_answers",{user_id:userId,question_hash:a.question_hash||a.questionHash,question:a.question||"",answer:a.answer||"",updated_at:a.updated_at||new Date().toISOString()},"user_id,question_hash");const apps=local.applications||[];for(const a of apps)await sbUpsert("jobpro_applications",{user_id:userId,job_id:a.job_id||null,url:a.url||"",company:a.company||"",title:a.title||"",status:a.status||"saved",applied_at:a.applied_at||null,notes:a.notes||"",match_score:a.match_score??null,resume_id:a.resume_id||null});const remoteProfiles=await sbQuery("jobpro_profiles","select=*&user_id=eq."+encodeURIComponent(userId));const remoteAnswers=await sbQuery("jobpro_saved_answers","select=*&user_id=eq."+encodeURIComponent(userId));const remoteApps=await sbQuery("jobpro_applications","select=*&user_id=eq."+encodeURIComponent(userId)+"&order=applied_at.desc");const mergedProfiles=[...profiles];for(const r of remoteProfiles||[]){const idx=mergedProfiles.findIndex(p=>p.name===r.name);const localP=idx>=0?mergedProfiles[idx]:{id:"remote_"+r.id,name:r.name};const merged={...localP,fullName:r.full_name,email:r.email,phone:r.phone,linkedin:r.links?.linkedin||"",github:r.links?.github||"",portfolio:r.links?.portfolio||"",answers:r.answers||{}};if(idx>=0)mergedProfiles[idx]=merged;else mergedProfiles.push(merged)}await storageSet({profiles:mergedProfiles,savedAnswers:remoteAnswers||[],applications:remoteApps||[],lastSyncAt:Date.now()});return{ok:true,profileCount:mergedProfiles.length,applicationCount:(remoteApps||[]).length}}
async function sbAi(action,input){return sbFetch("/functions/v1/ai",{method:"POST",body:JSON.stringify({action,input})})}
async function sbFetchJobs(query,location){return sbFetch("/functions/v1/fetch_jobs",{method:"POST",body:JSON.stringify({query,location})})}